name: lunar-e2e-after-ci-pipeline-97543cc38
on:
  push:
    paths: [".github/workflows/lunar-e2e-after-ci-pipeline-97543cc38.yml"]
permissions:
  contents: read
jobs:
  build:
    runs-on: localdev-e2e-test-38097564281-1-github-8-e2e
    steps:
      - run: '[ "${{ github.run_attempt }}" != 1 ] || { echo "attempt 1 fails so it can be re-run"; exit 1; }'
